version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: db_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DATASOURCE_PASSWORD}
      MYSQL_DATABASE: spring_db
      MYSQL_USER: root123
      MYSQL_PASSWORD: ${DATASOURCE_PASSWORD}
    ports:
      - "127.0.0.1:3356:3306"
    restart: always
  probation:
    image: probation
    container_name: probation-app
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - 8084:8084
    restart: always
    links:
      - db:mysql
      - kafka:kafka
    depends_on:
      - kafka
      - db
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://db_mysql/spring_db?createDatabaseIfNotExist=true"
      SPRING_DATASOURCE_USERNAME: root123
      SPRING_DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      SPRING_MAIL_USERNAME: ${MAIL_NAME}
      SPRING_MAIL_PASSWORD: ${MAIL_PASSWORD}

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
