version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: db_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DATASOURCE_PASSWORD}
      MYSQL_DATABASE_NAME: spring_db
      MYSQL_USER: root123
      MYSQL_PASSWORD: ${DATASOURCE_PASSWORD}
    ports:
      - "127.0.0.1:3356:3306"
    restart: always
  probation:
    image: probation
    container_name: probation-app
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - 8084:8084
    restart: always
    links:
      - db:mysql
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://db_mysql:3306/spring_db"
      SPRING_DATASOURCE_USERNAME: "root123"
      SPRING_DATASOURCE_PASSWORD: ${DATASOURCE_PASSWORD}
      SPRING_MAIL_USERNAME: ${MAIL_NAME}
      SPRING_MAIL_PASSWORD: ${MAIL_PASSWORD}
